# Copyright (c) Mixed Reality Toolkit Contributors
# Licensed under the BSD 3-Clause

name: '$(date:yyMM).$(date:dd)$(rev:rr)-MixedRealityToolkit-RC'
parameters:
- name: Sign
  type: boolean
  default: false

# schedules:
# - cron: "0 2 1,15 * *"
#   displayName: Run At 02:00 on the 1st and 15th of each month
#   # run even when there are no code changes
#   always: true
#   branches:
#     include:
#     - main
    
trigger: none
pr: none

variables:
  - template: Config/settings.yaml
  - name: Version.Revision
    value: $[counter(variables['ProjectVersion'], 1)]
  - name: Version.DateCode
    value: $[format('{0:yyMMdd}', pipeline.startTime)]
  - name: Version.DateCodeRevision
    value: $[counter(format('{0:yyMMdd}', pipeline.startTime), 0)]


resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: PipelineTools
    type: git
    endpoint: ToolsAccess
    name: tools.internal
    ref: 78ecf591964ecf511b4c7a0cd84d98ce11e8be16
  - repository: DocToolUnityProject
    type: git
    endpoint: ToolsAccess
    name: lib.doctools
    ref: 26723e6afa6d2adb44a734bd6ce0bc2bd90638b5

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Unity_2021.3.21f1_Pool
    sdl:
      sourceRepositoriesToScan:
        exclude:
        - repository: PipelineTools
        - repository: DocToolUnityProject
        
    stages:
    - stage: 'Build'
      jobs:
      - job: UnityValidation

        steps:
        - checkout: self
        - checkout: PipelineTools

        - powershell: Get-ChildItem -Path $(Build.SourcesDirectory) -recurse
          displayName: 'Initial source tree'

        - template: /Pipelines/Templates/1ES/unity.yaml@self
          parameters:
            Platform: Standalone